# base_link:
#   sensor_kit_base_link:
#     x: 0.0
#     y: 0.0
#     z: 0.0
#     roll: -0.00
#     pitch: 0.00
#     yaw: -0.00
base_link:
  sensor_kit_base_link:
    x: 0.66
    # x: 0.0
    y: 0.0
    z: 0.58
    # z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
